version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
     - 5432:5432
    
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 12345

  mongo:
    image: mongo
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345